### ISSUE TITLE
How to generalise code for arbitrary models?

### ISSUE THREAD

**Issue by Zephyrasgit** [IBM/model-sanitization#1]
Hi, I am currently adapting your code to test on my own dataset and ResNet18 model, but I realise your code is highly hard-coded for CIFAR10 and particular WideResNet models. Can you guide me through on how I can adapt this to suit my test?

**Comment by pinyuchen** [comment]
Hello @Zephyrasgit The main purpose of our repo is to provide reproducible results to our publication. If you are interested in using your own model other than we provided, you need to define/train/load your models and work on the mode connectivity code. You may find the repo of the original mode connectivity paper useful https://github.com/timgaripov/dnn-mode-connectivity/blob/master/README.md

**Comment by zpert** [comment]
Hello, for the idea of model connectivity, you can refer to the original model connectivity paper or our paper. Basically, during the implementation, you need to define three models with the same structure, and define the computation of the connected three models. This job is already done in our code. The original mode connectivity code includes various resnet and vgg models. If you do not find your model, you can define it by yourself using the basic modules in the code. The original code and our code have the basic part for the convolutional curve layers and other curve layers. You can choose the required basic parts and build your model.

**Comment by Zephyrasgit** [comment]
Thanks for the information, @pinyuchen and @zpert. I have some successes of using your code for my own dataset (not CIFAR10), and received very interesting results (backdoor attack accuracy decreased from 90% to 20% after curve finding procedure from Mode Connectivity). This work is very fascinating.

I will go ahead to see if I am able to generalise the code for arbitrary models, using the code from the original Mode Connectivity paper. Thanks for your advices!

**Comment by pinyuchen** [comment]
@Zephyrasgit Glad to know our method works smoothly for your model :)
